name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "53 8 * * 1"

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.3.2-xenial
          - swift:5.3.2-bionic
    container: ${{ matrix.image }}
    steps:
      - name: Install SQLite & PG Dev
        run: |
          apt-get update
          apt-get -y install libc6-dev make autoconf libtool pkg-config libxml2 apache2-dev
        # 2022-05-07(hh): We had this in the Travis install action,
        #                 might not be required anymore anyways: 
        # dirty hack to get Swift module for APR working on Linux
        # head -n -6 /usr/include/apr-1.0/apr.h > /tmp/zz-apr.h
        # echo ""                              >> /tmp/zz-apr.h
        # echo "// mod_swift build hack"       >> /tmp/zz-apr.h
        # echo "typedef int pid_t;"            >> /tmp/zz-apr.h
        # tail -n 6 /usr/include/apr-1.0/apr.h >> /tmp/zz-apr.h
        # sudo mv /usr/include/apr-1.0/apr.h /usr/include/apr-1.0/apr-original.h
        # sudo mv /tmp/zz-apr.h /usr/include/apr-1.0/apr.h
        # cat /usr/include/apr-1.0/apr.h # testing
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
  nextstep:
    runs-on: macos-latest
    steps:
      - name: Select latest available Xcode
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: 12.2
      # Likely doesn't work anymore, I think Homebrew b0rked proper Apache
      # modules a while back. We might rather want to install Apache from
      # the sources.
      - name: Install Apache via Homebrew
        run: |
          brew tap homebrew/core
          brew tap homebrew/services
          brew update
          brew install httpd
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Swift Debug Package
        run: swift build -c debug
      - name: Build Swift Release Package
        run: swift build -c release
